# Generated by Django 5.2.15 on 2026-07-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "emoji",
                    models.CharField(
                        default="💄", help_text="Banner emoji", max_length=10
                    ),
                ),
                (
                    "gradient",
                    models.CharField(
                        default="from-pink-500/20 via-rose-400/10 to-transparent",
                        help_text="Tailwind gradient classlari",
                        max_length=200,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="Bosilganda o'tish linki", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Bannerlar",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Ishlab chiqaruvchi davlat", max_length=80
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Bosh sahifada ko'rsatish"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendlar",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Emoji", max_length=10),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=12, null=True
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("skincare", "Teri parvarishi"),
                            ("makeup", "Makiyaj"),
                            ("perfume", "Parfyumeriya"),
                            ("haircare", "Soch parvarishi"),
                            ("bodycare", "Tana parvarishi"),
                        ],
                        default="skincare",
                        max_length=20,
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "Barcha teri turlari"),
                            ("dry", "Quruq"),
                            ("oily", "Yog'li"),
                            ("combination", "Aralash"),
                            ("normal", "Normal"),
                            ("sensitive", "Sezgir"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, help_text="Hajm, masalan 50 ml", max_length=50
                    ),
                ),
                (
                    "shade",
                    models.CharField(
                        blank=True,
                        help_text="Rang/ton, masalan 'Nude 02'",
                        max_length=80,
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(blank=True, help_text="Asosiy tarkib"),
                ),
                (
                    "shelf_life_months",
                    models.PositiveIntegerField(
                        blank=True, help_text="Yaroqlilik muddati (oy)", null=True
                    ),
                ),
                ("country_of_origin", models.CharField(blank=True, max_length=80)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Bosh sahifada ko'rsatish"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot rasmi",
                "verbose_name_plural": "Mahsulot rasmlari",
                "ordering": ["order"],
            },
        ),
    ]
